// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc364.Robot2016.subsystems;

import org.usfirst.frc364.Robot2016.RobotMap;
import org.usfirst.frc364.Robot2016.commands.*;

import edu.wpi.first.wpilibj.AnalogInput;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.VictorSP;
import edu.wpi.first.wpilibj.command.Subsystem;

public class driveSystem extends Subsystem {

    public final RobotDrive robotDrive = RobotMap.driveSystemrobotDrive;
    public final AnalogInput gyro = RobotMap.driveSystemgyro;
    
    public void drive(double left, double right) {
    	robotDrive.tankDrive(left, right);
    }

    public void initDefaultCommand() {	
    	setDefaultCommand(new driveCommand());
    }
}

