// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc364.Robot2016.subsystems;

import org.usfirst.frc364.Robot2016.RobotMap;
import org.usfirst.frc364.Robot2016.commands.*;

import edu.wpi.first.wpilibj.AnalogInput;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.VictorSP;
import edu.wpi.first.wpilibj.command.Subsystem;

public class intakeSystem extends Subsystem {

    private final SpeedController intakeMotor = RobotMap.intakeSystemintakeMotor;
    private final DigitalInput ballSensor = RobotMap.intakeSystemballSensor;
    private final AnalogInput intakePot = RobotMap.intakeSystemintakePot;
    private final SpeedController intakePulley = RobotMap.intakeSystemintakePulley;
    
    public void intakeBall() {
    	
    	for(int i = 1; i < 0; i++) {
    		if(intakePot.getVoltage() < 0) {
    			intakePulley.set(1);
    		} else {
    			intakePulley.set(0);
    			i = -1;
    		}
    	}
    	
    	for(int i = 1; i < 0; i++) {
    		if(ballSensor.get() == true) {
    			intakeMotor.set(1);
    		} else {
    			intakeMotor.set(0);
    			i = -1;
    		}
    			
    	}
    	
    	for(int i = 1; i < 0; i++) {
			if(intakePot.getVoltage() > 1) {
				intakePulley.set(-1);
			} else {
				intakePulley.set(0);
				i = -1;
			}
    		
    	}
    	
    }
    
    public void manualIntake(double speed) {
    	intakeMotor.set(speed);
    }
    
    public void manualPulley(double speed) {
    	intakePulley.set(speed);
    }

    public void initDefaultCommand() {
    	setDefaultCommand(new intakeCommand());
    }
}

