// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc364.Robot2016.subsystems;

import org.usfirst.frc364.Robot2016.Robot;
import org.usfirst.frc364.Robot2016.RobotMap;
import org.usfirst.frc364.Robot2016.commands.*;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.VictorSP;
import edu.wpi.first.wpilibj.command.Subsystem;

public class shootSystem extends Subsystem {

    private final SpeedController shootMotor = RobotMap.shootSystemshootMotor;
    private final SpeedController intakeMotor = RobotMap.intakeSystemintakeMotor;
    
    public void shoot() {
    	intakeMotor.set(-0.3);
    	Timer.delay(0.4);
    	intakeMotor.set(0);
    	shootMotor.set(1);
    	Timer.delay(1);
    	intakeMotor.set(1);
    	Timer.delay(0.5);
    	intakeMotor.set(0);
    }

    public void initDefaultCommand() {
    	setDefaultCommand(new shootCommand());
    }
}
