// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc364.Robot2016.commands;

import edu.wpi.first.wpilibj.command.Command;

import org.usfirst.frc364.Robot2016.Robot;
import org.usfirst.frc364.Robot2016.subsystems.hangSystem;

public class hangCommand extends Command {

	boolean up = Robot.oi.controller.getRawButton(4);
	boolean down = Robot.oi.controller.getRawButton(1);
	boolean left = Robot.oi.controller.getRawButton(3);
	boolean right = Robot.oi.controller.getRawButton(2);
	
    public hangCommand() {
    	requires(Robot.hangSystem);
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {	
    	if(up == true) {
    		hangSystem.manualFlip(1);
    	} if(down == true) {
    		hangSystem.manualFlip(-1);
    	} else {
    		hangSystem.manualFlip(0);
    	}
    	
    	if(left == true) {
    		hangSystem.manualWench(1);
    	} if(right == true) {
    		hangSystem.manualWench(-1);
    	} else {
    		hangSystem.manualWench(0);
    	}
    	
    	
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
