// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc364.Robot2016.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc364.Robot2016.Robot;

public class intakeCommand extends Command {

    public intakeCommand() {
    	requires(Robot.intakeSystem);
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	boolean intakeBall = Robot.oi.controller.getRawButton(6);
    	double yaxis = Robot.oi.controller.getRawAxis(1);
    	double xaxis = Robot.oi.controller.getRawAxis(5);
    	
    	//This runs the manual intake
    	if(yaxis > 0.05 || yaxis < -0.05) { 
        	Robot.intakeSystem.manualIntake(yaxis);
    	} else {
    		Robot.intakeSystem.manualIntake(0);
    	}
    	//This runs the manual pulley
    	if(xaxis > 0.05 || xaxis < -0.05) {
    		Robot.intakeSystem.manualPulley(xaxis);
    	} else {
    		Robot.intakeSystem.manualPulley(0);
    	}
    	/*
    	//This runs the intake ball sequence
    	if(intakeBall == true) {
    		Robot.intakeSystem.intakeBall();
    	}
    	*/
    	
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after is Finished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
