// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc364.Robot2016;

import org.usfirst.frc364.Robot2016.commands.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.JoystickButton;

import org.usfirst.frc364.Robot2016.subsystems.*;

public class OI {
	
    public Joystick leftStick;
    public Joystick rightStick;
    public Joystick controller;
    public JoystickButton intakeBall;
    public JoystickButton flipHangBars;
    public JoystickButton extendHangBars;
    public JoystickButton hangFromCastle;
    public JoystickButton flipManualUp;
    public JoystickButton flipManualDown;
    public JoystickButton wenchManualUp;
    public JoystickButton wenchManualDown;
    public JoystickButton shoot;
    public JoystickButton rearCamSelect;
    public JoystickButton frontCamSelect;

    public OI() {

        controller = new Joystick(2);
        
        intakeBall = new JoystickButton(controller, 5);
        intakeBall.whenPressed(new intakeCommand());
        
        flipHangBars = new JoystickButton(controller, 7);
        flipHangBars.whenPressed(new flipCommand());
        
        extendHangBars = new JoystickButton(controller, 8);
        extendHangBars.whenPressed(new flipCommand());
        
        hangFromCastle = new JoystickButton(controller, 9);
        hangFromCastle.whenPressed(new hangCommand());
        
        flipManualUp = new JoystickButton(controller, 4);
        flipManualUp.whenPressed(new flipCommand());
        
        flipManualDown = new JoystickButton(controller, 1);
        flipManualDown.whenPressed(new flipCommand());
        
        wenchManualUp = new JoystickButton(controller, 2);
        wenchManualUp.whenPressed(new hangCommand());
        
        wenchManualDown = new JoystickButton(controller, 3);
        wenchManualDown.whenPressed(new hangCommand());
        
        shoot = new JoystickButton(controller, 6);
        shoot.whenPressed(new shootCommand());
        
        rightStick = new Joystick(1);
        
        rearCamSelect = new JoystickButton(rightStick, 1);
        rearCamSelect.whenPressed(new cameraCommand());
        
        leftStick = new Joystick(0);
        
        frontCamSelect = new JoystickButton(leftStick, 1);
        frontCamSelect.whenPressed(new cameraCommand());
        
    }

    public Joystick getleftStick() {
        return leftStick;
    }

    public Joystick getrightStick() {
        return rightStick;
    }

    public Joystick getcontroller() {
        return controller;
    }

}

