// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc364.Robot2016;

import org.usfirst.frc364.Robot2016.commands.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Joystick;
import org.usfirst.frc364.Robot2016.subsystems.*;

public class OI {
	
    public Joystick leftStick;
    public Joystick rightStick;
    public Joystick controller;

    public OI() {

        controller = new Joystick(2);
        
        rightStick = new Joystick(1);
        
        leftStick = new Joystick(0);
        
    }

    public Joystick getleftStick() {
        return leftStick;
    }

    public Joystick getrightStick() {
        return rightStick;
    }

    public Joystick getcontroller() {
        return controller;
    }

}

